-- 코드를 입력하세요
SELECT PT_NAME,PT_NO, GEND_CD, AGE, IFNULL(Tlno,'NONE') AS TLNO
FROM PATIENT
Where GEND_CD ='W' and AGE<=12
ORDER BY Age DESC, Pt_name ASC

-- 코드를 입력하세요
SELECT PT_NAME,PT_NO, GEND_CD, AGE, COALESCE(Tlno,'NONE') AS TLNO
FROM PATIENT
Where GEND_CD ='W' and AGE<=12
ORDER BY Age DESC, Pt_name ASC
