-- 코드를 입력하세요
SELECT TITLE,A.BOARD_ID,REPLY_ID,B.WRITER_ID,B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') 
    as CREATED_DATE
    FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_REPLY AS B 
    ON A.BOARD_ID = B.BOARD_ID
    WHERE A.CREATED_DATE LIKE  '2022-10%' 
    ORDER BY B.CREATED_DATE ASC, A.TITLE ASC
    
    
        # WHERE YEAR(A.CREATED_DATE) = 2022
    #     AND MONTH(A.CREATED_DATE) = 10