-- 코드를 입력하세요
# SELECT * FROM FIRST_HALF
SELECT F.FLAVOR
    FROM FIRST_HALF f 
    JOIN ICECREAM_INFO i ON f.FLAVOR = i.FLAVOR
    WHERE f.TOTAL_ORDER > 3000 
        and i.INGREDIENT_TYPE ='fruit_based'
    ORDER BY TOTAL_ORDER desc